# Generated by Django 4.0.4 on 2022-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='price',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='price_new',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
