# Generated by Django 4.0.4 on 2022-05-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_price_contact_price_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price_new',
            field=models.IntegerField(),
        ),
    ]
