# Generated by Django 4.0.4 on 2022-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_rename_price_new_contact_price_new1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price_new1',
            field=models.IntegerField(),
        ),
    ]
