# Generated by Django 4.0.4 on 2022-05-23 12:23

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_doors_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, choices=[('1', 'Хетчбек'), ('2', 'Седан'), ('3', 'Позашляховик'), ('4', 'Універсал'), ('5', 'Купе'), ('', 'Кабріолет')], max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_1',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_10',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_2',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_3',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_4',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_5',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_6',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_7',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_8',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_9',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cruise Control', 'Круїз-контроль'), ('Audio Interface', 'Аудіоінтерфейс'), ('Airbags', 'Подушки безпеки'), ('Air Conditioning', 'Кондиціонер'), ('Seat Heating', 'Обігрів сидінь'), ('Alarm System', 'Сигналізація'), ('ParkAssist', 'Парктронік'), ('Power Steering', 'Гідропідсилювач керма'), ('Reversing Camera', 'Камера заднього виду'), ('Auto Start/Stop', 'Система Старт/Стоп'), ('Rain sensor', 'Сенсор дощу'), ('Bluetooth Handset', 'Bluetooth')], max_length=170),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('1', 'Дизель'), ('2', 'Бензин'), ('3', 'Бензин/Газ'), ('4', 'Газ'), ('5', 'Електро')], max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='kilometers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone_owners',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='region',
            field=models.CharField(choices=[('AK', 'Кримcька'), ('AA', 'Київська'), ('AB', 'Вінницька'), ('AC', 'Волинська'), ('AE', 'Дніпропетровька'), ('AH', 'Донецька'), ('AM', 'Житомирська'), ('AO', 'Закарпатська'), ('AP', 'Запорізьська'), ('AT', 'Івано-Франківська'), ('AX', 'Харківська'), ('BA', 'Кіровоградська'), ('BB', 'Луганська'), ('BC', 'Львівська'), ('BE', 'Миколаївська'), ('BH', 'Одеська'), ('BI', 'Полтавська'), ('BK', 'Рівненська'), ('BM', 'Сумська'), ('BO', 'Тернопільська'), ('BT', 'Херсонська'), ('BX', 'Хмельницька'), ('CA', 'Черкаська'), ('CB', 'Чернівецька'), ('CE', 'Чернігівська')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Mechanics', 'Механіка'), ('Automatic', 'Автоматична')], max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year'),
        ),
    ]
