# Generated by Django 4.0.4 on 2022-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_body_style_alter_car_car_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, choices=[('1', 'Хетчбек'), ('2', 'Седан'), ('3', 'Позашляховик'), ('4', 'Універсал'), ('5', 'Купе'), ('6', 'Кабріолет')], default=None, max_length=150),
        ),
    ]
