# Generated by Django 4.0.4 on 2022-05-23 20:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_body_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_new',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, choices=[('Хетчбек', 'Хетчбек'), ('Седан', 'Седан'), ('Позашляховик', 'Позашляховик'), ('Універсал', 'Універсал'), ('Купе', 'Купе'), ('Кабріолет', 'Кабріолет')], max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Круїз-контроль', 'Круїз-контроль'), ('Аудіоінтерфейс', 'Аудіоінтерфейс'), ('Подушки безпеки', 'Подушки безпеки'), ('Кондиціонер', 'Кондиціонер'), ('Обігрів сидінь', 'Обігрів сидінь'), ('Сигналізація', 'Сигналізація'), ('Парктронік', 'Парктронік'), ('Гідропідсилювач керма', 'Гідропідсилювач керма'), ('Камера заднього виду', 'Камера заднього виду'), ('Система Старт/Стоп', 'Система Старт/Стоп'), ('Сенсор дощ', 'Сенсор дощу'), ('Bluetooth', 'Bluetooth')], max_length=179),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Дизель', 'Дизель'), ('Бензин', 'Бензин'), ('Бензин/Газ', 'Бензин/Газ'), ('Газ', 'Газ'), ('Електро', 'Електро')], max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='region',
            field=models.CharField(choices=[('Кримcька', 'Кримcька'), ('Київська', 'Київська'), ('Вінницька', 'Вінницька'), ('Волинська', 'Волинська'), ('Дніпропетровька', 'Дніпропетровька'), ('Донецька', 'Донецька'), ('Житомирська', 'Житомирська'), ('Закарпатська', 'Закарпатська'), ('Запорізьська', 'Запорізьська'), ('Івано-Франківська', 'Івано-Франківська'), ('Харківська', 'Харківська'), ('Кіровоградська', 'Кіровоградська'), ('Луганська', 'Луганська'), ('Львівська', 'Львівська'), ('Миколаївська', 'Миколаївська'), ('Одеська', 'Одеська'), ('Полтавська', 'Полтавська'), ('Рівненська', 'Рівненська'), ('Сумська', 'Сумська'), ('Тернопільська', 'Тернопільська'), ('Херсонська', 'Херсонська'), ('Хмельницька', 'Хмельницька'), ('Черкаська', 'Черкаська'), ('Чернівецька', 'Чернівецька'), ('Чернігівська', 'Чернігівська')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Механіка', 'Механіка'), ('Автоматична', 'Автоматична')], max_length=150),
        ),
    ]
