# Generated by Django 4.0.4 on 2022-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_price_new_alter_car_body_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_new',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
