# Generated by Django 4.0.4 on 2022-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_price_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Механіка', 'Механіка'), ('Автомат', 'Автомат')], max_length=150),
        ),
    ]
