# Generated by Django 4.0.4 on 2022-05-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='brand',
        ),
    ]
